name: Build and Test

on:
  push:
    branches: [main]
    paths-ignore:
      #      - .github/**
      - Dockerfile
  pull_request:
    branches: [main]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@main

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Generate package-lock.json
        run: npm install --package-lock-only

      - name: Clean node_modules and lock
        run: |
          rm -rf node_modules package-lock.json frontend/node_modules frontend/package-lock.json frontend/docs/node_modules frontend/docs/package-lock.json

      - name: Install dependencies
        run: |
          npm install -g npm
          npm install
          cd frontend
          npm install
          cd docs
          npm install

      - name: Test
        run: |
          npm test -- --detectOpenHandles
          cd frontend
          npm install -g vitest
          npm install -g @testing-library/jest-dom
          npm install -g @testing-library/react
          npm install -g @testing-library/user-event
          npm install -g @babel/preset-env
          npm install -g @babel/preset-react
          npm install -g @babel/preset-typescript
          npm install -g @babel/preset-stage-2
          npm install -g @babel/preset-stage-3
          npx vitest

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@main
        with:
          name: build-artifacts
          path: |
            dist/
            frontend/dist/
            frontend/docs/build/
          retention-days: 30

      - name: Cache build artifacts
        uses: actions/cache@main
        with:
          path: |
            dist
            node_modules
            frontend/node_modules
            frontend/docs/node_modules
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-
