name: Sync from Happy-TTS

on:
  push:
  schedule:
    - cron: "0 2 * * *" # 每天凌晨2点
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 检出本仓库
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: 安装依赖
        run: npm install simple-git fs-extra

      - name: 执行同步脚本
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: node scripts/sync-repo.js $GITHUB_TOKEN
